"""Render the model card from the measured release artifacts."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from masriswitch.config import Paths
from masriswitch.data.registry import load_sources


def _read(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"Expected JSON object: {path}")
    return data


def _pct(value: float) -> str:
    return f"{value * 100:.2f}%"


def main() -> None:
    paths = Paths(Path.cwd())
    train = _read(paths.artifacts / "train_manifest.json")
    results = _read(paths.artifacts / "eval_metrics.json")
    audit = _read(paths.artifacts / "data_audit.json")
    selection = _read(paths.artifacts / "checkpoint_selection.json")
    e0, e1 = results.get("E0"), results.get("E1")
    sources = load_sources(paths.root / "configs/sources.yaml")
    source_ids = train.get("training_source_ids")
    if (
        not isinstance(e0, dict)
        or not isinstance(e1, dict)
        or e0.get("complete") is not True
        or e1.get("complete") is not True
        or e0.get("overall", {}).get("count") != 489
        or e1.get("overall", {}).get("count") != 489
        or e0.get("plan_sha256") != e1.get("plan_sha256")
        or e1.get("model_sha256") != train.get("checkpoint_sha256")
        or selection.get("selected_checkpoint_sha256") != train.get("checkpoint_sha256")
        or source_ids != ["d1"]
        or not all(sources[source_id].release_safe for source_id in source_ids)
        or audit.get("complete") is not True
        or audit.get("release_safe") is not True
    ):
        raise ValueError("Measured, selected, release-safe E1 is required")
    m0, m1 = e0["metrics"], e1["metrics"]
    lines = [
        "---",
        "license: apache-2.0",
        "language:",
        "- ar",
        "- en",
        "tags:",
        "- text-to-speech",
        "- code-switching",
        "- egyptian-arabic",
        "base_model: silma-ai/silma-tts",
        "---",
        "",
        "# MasriSwitch-TTS model card",
        "",
        "## Status and intended use",
        "",
        "Experimental Egyptian Arabic and English code-switched text-to-speech "
        "for research and voice-agent prototyping. Audio is AI-generated. "
        "Use a reference voice only with documented speaker consent; "
        "no public reference recording is included.",
        "",
        "## Base, training data, and provenance",
        "",
        "Base checkpoint: SILMA TTS v1 (Apache-2.0 weights), using F5-TTS 1.1.7 "
        "(MIT code). Training uses only audited D1 rows labeled CC BY 4.0 "
        "and generated by the dataset author. Noncommercial D1 rows were excluded.",
        f"D1 revision: `{sources['d1'].revision}`; selected train rows: "
        f"{len(train['training_sample_ids'])}; seed: {train['seed']}.",
        f"Selected checkpoint SHA256: `{train['checkpoint_sha256']}`. "
        "Checkpoint was chosen on validation prompts by English EER, "
        "then code-switch WER, with an overall Arabic CER guardrail.",
        "Attribution: Abdelrahman R. Hashem, *Synthetic Arabic-English "
        "Code-Switched Speech for ASR* (2026). See `NOTICE` and the data audit.",
        "",
        "## Evaluation",
        "",
        "The same 189 validation and 300 locked MasriSwitch-Bench prompts, private "
        "reference voice, 16 inference steps, and pinned independent ASR were used for E0/E1.",
        "",
        "| Model | Code-switch WER | English EER | Arabic-only CER | "
        "Critical entity accuracy | Mean speaker cosine | Mean RTF |",
        "|---|---:|---:|---:|---:|---:|---:|",
        f"| E0 SILMA | {_pct(m0['cs_wer'])} | {_pct(m0['english_eer'])} | "
        f"{_pct(m0['ar_cer'])} | {_pct(m0['critical_entity_accuracy'])} | "
        f"{m0['speaker_similarity']:.3f} | {m0['mean_rtf']:.3f} |",
        f"| E1 selected | {_pct(m1['cs_wer'])} | {_pct(m1['english_eer'])} | "
        f"{_pct(m1['ar_cer'])} | {_pct(m1['critical_entity_accuracy'])} | "
        f"{m1['speaker_similarity']:.3f} | {m1['mean_rtf']:.3f} |",
        "",
        "These metrics are ASR proxies, not human pronunciation or naturalness "
        "scores. See `EVALUATION.md` for confidence intervals and errors.",
        "",
        "## Limitations and misuse",
        "",
        "Training speech is synthetic and has no speaker IDs, so real Egyptian "
        "speaker, accent, and acoustic robustness are unproven. English entities, "
        "numbers, and dates can be mispronounced. Do not use for consequential "
        "decisions without human verification. Do not impersonate, deceive, or "
        "commit fraud. Disclose generated audio and obtain consent before "
        "synthesizing a custom voice.",
        "",
    ]
    output = paths.reports / "MODEL_CARD_DRAFT.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps({"model_card": str(output), "checkpoint_sha256": train["checkpoint_sha256"]}))


if __name__ == "__main__":
    main()
